//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilions()
        {
            this.Rents = new HashSet<Rents>();
        }
    
        public string ID_Pavilion { get; set; }
        public int ID_SC { get; set; }
        public int Floor { get; set; }
        public int Status { get; set; }
        public double Square { get; set; }
        public decimal Cost_per_square_meter { get; set; }
        public double Cofficient_of_added_value { get; set; }
    
        public virtual Status_Pavilion Status_Pavilion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rents> Rents { get; set; }
        public virtual Store_Centers Store_Centers { get; set; }
    }
}
