//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int ID_rent { get; set; }
        public int ID_tenant { get; set; }
        public int ID_SC { get; set; }
        public int ID_Employer { get; set; }
        public string ID_pavilion { get; set; }
        public int Status { get; set; }
        public System.DateTime Start_rent { get; set; }
        public System.DateTime Finish_rent { get; set; }
    
        public virtual Employers Employers { get; set; }
        public virtual Pavilions Pavilions { get; set; }
        public virtual Status_Rent Status_Rent { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
